// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe-shop-test/internal/logic/admin"
	_ "goframe-shop-test/internal/logic/position"
	_ "goframe-shop-test/internal/logic/rotation"
)
