// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe-shop-test/internal/logic/admin"
	_ "goframe-shop-test/internal/logic/bizctx"
	_ "goframe-shop-test/internal/logic/data"
	_ "goframe-shop-test/internal/logic/login"
	_ "goframe-shop-test/internal/logic/middleware"
	_ "goframe-shop-test/internal/logic/position"
	_ "goframe-shop-test/internal/logic/role"
	_ "goframe-shop-test/internal/logic/rotation"
	_ "goframe-shop-test/internal/logic/session"
)
