// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe-shop-test/internal/logic/admin"
	_ "goframe-shop-test/internal/logic/article"
	_ "goframe-shop-test/internal/logic/bizctx"
	_ "goframe-shop-test/internal/logic/category"
	_ "goframe-shop-test/internal/logic/coupon"
	_ "goframe-shop-test/internal/logic/data"
	_ "goframe-shop-test/internal/logic/file"
	_ "goframe-shop-test/internal/logic/goods"
	_ "goframe-shop-test/internal/logic/goods_options"
	_ "goframe-shop-test/internal/logic/login"
	_ "goframe-shop-test/internal/logic/middleware"
	_ "goframe-shop-test/internal/logic/permission"
	_ "goframe-shop-test/internal/logic/position"
	_ "goframe-shop-test/internal/logic/role"
	_ "goframe-shop-test/internal/logic/rotation"
	_ "goframe-shop-test/internal/logic/session"
	_ "goframe-shop-test/internal/logic/user_coupon"
)
